#!/bin/sh

WORK_DIR="/home/encoder/w"

# make sure we are in the working directory
if [ "$(pwd)" != "$WORK_DIR" ]; then
  echo "ERROR: MUST BE IN DIRECTORY: /home/encoder/w" >&2
  exit 1
fi

echo "Running Cleanup !!!!!!"

mv ${WORK_DIR}/done_archive/sk/out/*.mp4 ${WORK_DIR}/done_archive/sk/old/

rm -f ${WORK_DIR}/*.mp4
rm -f ${WORK_DIR}/*.mp3
rm -f ${WORK_DIR}/*.mov
rm -f ${WORK_DIR}/ffmpeg2pass*
ssh USER@REMOTE_HOST 'cd REMOTE_DIRECTORY;./.cleanup'
