#!/bin/bash

if [ $# -ne 1 ] && [ ! -f "$1" ]; then
  echo "Usage: $0  Source_Folder/file_name" >&2
  echo "Ex: $0  friday/NN_702h264.mov" >&2
  exit 1
fi

pv=/usr/bin/pv

source_dir="$(cut -d '/' -f1 <<< "${1}")"
file_name="$(cut -d '/' -f2 <<< "${1}")"

$pv "${source_dir}/${file_name}" > "${file_name}"

ffmpeg -i ./"${file_name}"  -vn -ac 2 -ar 44100 -ab 256k -f mp3 ./"${file_name/.mov/.mp3}"
./domenic_upload ./"${file_name/.mov/.mp3}"
./domenic_upload ./"${file_name}"
