#!/bin/bash

pv=/usr/bin/pv
ffprobe=/usr/bin/ffprobe
opts=( -v error -select_streams v -show_entries stream=r_frame_rate -of csv=p=0 )

if [ "$#" -ne "3" ] ; then
  echo "Usage: $0 YYYY-MM-DD Source_Folder  segment_number" >&2
  echo "Ex: $0 2014-03-09 today  2" >&2
  echo "Ex: $0 2014-11-28 weekend  1" >&2
  echo "Ex: $0 2014-12-24 holiday/xmas24 5" >&2
  exit 1
fi

name_date="$1"
source_dir="$2"
segment_idx="$3"

# ${ffprobe_frame_rate} should be of the form num/num.
# Ex. 30000/1001 or 2997/100
ffprobe_frame_rate="$(${ffprobe} "${opts[@]}" "${source_dir}/${segment_idx}.mov")"

# Divide the numbers in ${ffprobe_frame_rate}
real_frame_rate=$((ffprobe_frame_rate))

# make sure the frame rate (rounded down) is 29
if [ ${real_frame_rate} -ne 29 ]; then
	echo "ERROR!!!! Segment does not have a floor frame rate of 29 !!" >&2
	echo "Frame rate is ${real_frame_rate}" >&2
	exit 1
fi

${pv} "${source_dir}/${segment_idx}.mov" > "female_show_${name_date}_hd_${segment_idx}.mov"

if [ "$?" -eq "0" ]; then
	./sk_encode.sh female_show_${name_date}_hd_${segment_idx}.mov
else
	echo "$0 ERROR: cp from working directory failed" >&2
	exit 1
fi
