#!/bin/bash

pv=/usr/bin/pv
ffprobe=/usr/bin/ffprobe
frame_opts=( -v error -select_streams v -show_entries stream=r_frame_rate -of csv=p=0 )
codec_opts=( -v error -select_streams v -show_entries stream=codec_name \
	-of default=noprint_wrappers=1:nokey=1 )

if [ $# -ne 3 ] ; then
  echo "Usage: $0 YYYY-MM-DD Source_Folder  segment_number" >&2
  echo "Ex: $0 2014-03-09 today  2" >&2
  echo "Ex: $0 2014-11-28 weekend  1" >&2
  echo "Ex: $0 2014-12-24 holiday/xmas24 5" >&2
  exit 1
fi

name_date="$1"
source_dir="$2"
segment_idx="$3"

# ${ffprobe_frame_rate} should be of the form num/num.
# Ex. 30000/1001 or 2997/100
ffprobe_frame_rate="$(${ffprobe} "${frame_opts[@]}" "${source_dir}/${segment_idx}.mov")"

# Get the frame rate to 2 decimal places
real_frame_rate=$(echo "scale=2; ${ffprobe_frame_rate}" | bc)

# make sure the frame rate is 29.97
if [[ "${real_frame_rate}" != "29.97" ]]; then
	echo "ERROR!!!! Segment does not have a floor frame rate of 29 !!" >&2
	echo "Frame rate is ${real_frame_rate}" >&2
	exit 1
fi

# Check video codec of segment; should be Apple ProRes 422 ("prores")
video_codec="$(${ffprobe} "${codec_opts[@]}" "${source_dir}/${segment_idx}.mov")"

if [[ "$video_codec" != "prores" ]]; then
	echo "ERROR!!!! Segment was not encoded with Apple ProRes 422 !!" >&2
	echo "Video codec is ${video_codec}" >&2
	exit 1
fi

${pv} "${source_dir}/${segment_idx}.mov" > "female_show_${name_date}_hd_${segment_idx}.mov"

if [ $? -eq 0 ]; then
	./sk_encode.sh female_show_${name_date}_hd_${segment_idx}.mov
else
	echo "$0 ERROR: cp from working directory failed" >&2
	exit 1
fi
