#!/bin/bash

usage="Usage: $0 Source_Folder/File_Name"

# must be in the working directory
if [ "$(pwd)" != "/home/encoder/w" ]; then
	echo "ERROR! MUST BE IN DIRECTORY: /home/encoder/w" >&2
	exit 1
fi

if [ "$#" -ne 1 ]; then
	echo "$usage" >&2
	echo "Ex: $0 today/DP_Feb09.mov" >&2
	echo "Ex: $0 weekend/DP_Mar12.mov" >&2
	echo "Ex: $0 holiday/DP_Dec24.mov" >&2
	exit 1
fi

full_date="$(date +%Y-%m-%d)"

# Group 1 is the folder. Group 2 is DP filename.
# Group 3 is the abbreviated month name. Group 4 is the day. 
# today DP_Mar03.mov Mar 03 ------- today/DP_Mar03.mov
regex="(today|friday|weekend|holiday)/(DP_([[:alpha:]]{3})([[:digit:]]{2})\.mov)"

if [[ ! "$1" =~ $regex ]]; then
	echo "$0 ERROR: I think the DP was named incorrectly..." >&2
	exit 1
fi

source_dir=${BASH_REMATCH[1]}
old_name=${BASH_REMATCH[2]}
month_str=${BASH_REMATCH[3]}
month_num=${BASH_REMATCH[4]}

new_name="program_promo_hd_welcome_${month_str}${month_num}.mov"

#cp ${source_dir}/${old_name} ${new_name}
cp $1 ${new_name}
./sk_encode.sh ${new_name}
