#!/bin/bash

usage="Usage: $0" 

# must be in the working directory
if [ "$(pwd)" != "/home/encoder/w" ]; then
	echo "ERROR! MUST BE IN DIRECTORY: /home/encoder/w" >&2
	exit 1
fi

if [ "$#" -gt 0 ]; then
	echo "$usage" >&2
	exit 1
fi

weekday_name="$(date +%A)"
month="$(date +%b%d)"
month_str="$(date +%b)"
month_num="$(date +%d)"
full_date="$(date +%Y-%m-%d)"

# Day of the week can only be a weekday.
if [ "$weekday_name" == "Saturday" ] || [ "$weekday_name" == "Sunday" ]; then
	echo "There's no daily promo on Saturday or Sunday!!! \
	Only run this script from Monday to Friday." >&2
	exit 1
elif [ "$weekday_name" == "Friday" ]; then
	source_dir="friday"
else
	source_dir="today"
fi

file_path="${source_dir}/DP_${month}.mov"
 
if [[ ! -f "$file_path" ]]; then
	echo "$0 ERROR: DP not found in directory ${source_dir}!!!" >&2
	exit 1
fi

new_name="${full_date}_DailyPromo.mov"

echo "Filename is: $new_name !!!!!!"
echo "$file_path"

cp $file_path ${new_name}
./upload2SK ${new_name}
