#!/bin/sh

if [ "$#" -ne 3 ] ; then
  echo "Usage: $0  Source_Folder file_name  new_name" >&2
  echo "Ex: $0  today DP_Feb09.mov program_promo_hd_welcome_6937.mov" >&2
  echo "Ex: $0 weekend DP_Mar12.mov program_promo_hd_welcome_7012.mov" >&2
  echo "Ex: $0 holiday/xmas24  DP_Dec24.mov program_promo_hd_welcome_7233.mov" >&2
  exit 1
fi


source_dir=$1
old_name=$2
new_name=$3

cp  ${source_dir}/${old_name}  ${new_name}
./sk_encode.sh ${new_name}
